### ISSUE TITLE
推荐几个库

### ISSUE THREAD

**Issue by ltttttttttttt** [simplepeng/LearningCompose#1]
kmp跨平台的compose控件库: https://github.com/ltttttttttttt/ComposeViews
kmp跨平台的网络请求封装,类似Retrofit: https://github.com/ltttttttttttt/LazyPeopleHttp
kmp跨平台的给bean加上可被compose监听的能力: https://github.com/ltttttttttttt/Buff

**Comment by simplepeng** [comment]
@ltttttttttttt 已收录
